/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "alu.v:1.1-26.10" *)
module alu(A, B, ALU_Sel, Result);
  wire _000_;
  wire _001_;
  wire [1:0] _002_;
  wire [1:0] _003_;
  wire [1:0] _004_;
  wire [1:0] _005_;
  wire [1:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [15:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [15:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [3:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _016_;
  (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _017_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [3:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  (* unused_bits = "3" *)
  wire [3:0] _021_;
  (* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _022_;
  (* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _023_;
  (* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _024_;
  (* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _025_;
  (* src = "alu.v:2.17-2.18" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "alu.v:4.17-4.24" *)
  input [1:0] ALU_Sel;
  wire [1:0] ALU_Sel;
  (* src = "alu.v:3.17-3.18" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "alu.v:5.22-5.28" *)
  output [3:0] Result;
  wire [3:0] Result;
  assign _001_ = ~ALU_Sel[1];
  assign _000_ = ~ALU_Sel[0];
  assign _011_[8] = ~_020_[0];
  assign _008_ = _000_ |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *)  _001_;
  assign _009_ = ALU_Sel[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *)  _001_;
  assign _010_ = _000_ |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *)  ALU_Sel[1];
  assign _002_[0] = _012_[3] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[7];
  assign _002_[1] = _012_[11] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[15];
  assign _014_[3] = _002_[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _002_[1];
  assign _003_[0] = _012_[2] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[6];
  assign _003_[1] = _012_[10] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[14];
  assign _014_[2] = _003_[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _003_[1];
  assign _004_[0] = _012_[1] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[5];
  assign _004_[1] = _012_[9] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[13];
  assign _014_[1] = _004_[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _004_[1];
  assign _005_[0] = _012_[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[4];
  assign _005_[1] = _012_[8] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[12];
  assign _014_[0] = _005_[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _005_[1];
  assign _006_[0] = _013_[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _013_[1];
  assign _006_[1] = _013_[2] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _013_[3];
  assign _017_ = _006_[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _006_[1];
  assign _007_ = ALU_Sel[0] |(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *)  ALU_Sel[1];
  assign _013_[0] = ~(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *) _008_;
  assign _013_[1] = ~(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *) _009_;
  assign _013_[2] = ~(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *) _010_;
  assign _013_[3] = ~(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12" *) _007_;
  assign Result[0] = _017_ ? (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _014_[0] : 1'hx;
  assign Result[1] = _017_ ? (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _014_[1] : 1'hx;
  assign Result[2] = _017_ ? (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _014_[2] : 1'hx;
  assign Result[3] = _017_ ? (* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _014_[3] : 1'hx;
  assign _018_[0] = ~(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) B[0];
  assign _018_[1] = ~(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) B[1];
  assign _018_[2] = ~(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) B[2];
  assign _018_[3] = ~(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) B[3];
  assign _011_[2] = A[2] |(* src = "alu.v:18.25-18.30" *)  B[2];
  assign _011_[3] = A[3] |(* src = "alu.v:18.25-18.30" *)  B[3];
  assign _012_[12] = _011_[12] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[3];
  assign _012_[13] = _011_[13] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[3];
  assign _012_[14] = _011_[14] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[3];
  assign _012_[15] = _011_[15] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[3];
  assign _012_[8] = _011_[8] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[2];
  assign _012_[9] = _011_[9] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[2];
  assign _012_[10] = _011_[10] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[2];
  assign _012_[11] = _011_[11] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[2];
  assign _012_[4] = _011_[4] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[1];
  assign _012_[5] = _011_[5] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[1];
  assign _012_[6] = _011_[6] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[1];
  assign _012_[7] = _011_[7] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[1];
  assign _012_[0] = _011_[0] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[0];
  assign _012_[1] = _011_[1] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[0];
  assign _012_[2] = _011_[2] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[0];
  assign _012_[3] = _011_[3] &(* src = "alu.v:0.0-0.0|alu.v:10.5-22.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _013_[0];
  assign _011_[13] = _016_[1] ^(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _011_[4];
  assign _011_[14] = _016_[2] ^(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _015_[1];
  assign _011_[15] = _016_[3] ^(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _015_[2];
  assign _011_[12] = B[0] ^(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  A[0];
  assign _016_[1] = B[1] ^(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  A[1];
  assign _016_[2] = B[2] ^(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  A[2];
  assign _016_[3] = B[3] ^(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  A[3];
  assign _011_[4] = B[0] &(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  A[0];
  assign _011_[5] = B[1] &(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  A[1];
  assign _011_[6] = B[2] &(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  A[2];
  assign _011_[7] = B[3] &(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  A[3];
  assign _011_[9] = _020_[1] ^(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _019_[0];
  assign _011_[10] = _020_[2] ^(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _019_[1];
  assign _011_[11] = _020_[3] ^(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _019_[2];
  assign _020_[0] = A[0] ^(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _018_[0];
  assign _020_[1] = A[1] ^(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _018_[1];
  assign _020_[2] = A[2] ^(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _018_[2];
  assign _020_[3] = A[3] ^(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  _018_[3];
  assign _021_[0] = A[0] &(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _018_[0];
  assign _021_[1] = A[1] &(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _018_[1];
  assign _021_[2] = A[2] &(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  _018_[2];
  assign _022_ = _016_[1] &(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _011_[4];
  assign _023_ = _016_[2] &(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _015_[1];
  assign _015_[1] = _011_[5] |(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _022_;
  assign _015_[2] = _011_[6] |(* src = "alu.v:12.25-12.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _023_;
  assign _024_ = _020_[1] &(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _019_[0];
  assign _025_ = _020_[2] &(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _019_[1];
  assign _019_[0] = _021_[0] |(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.10-231.28" *)  _020_[0];
  assign _019_[1] = _021_[1] |(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _024_;
  assign _019_[2] = _021_[2] |(* src = "alu.v:14.25-14.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _025_;
  assign _011_[0] = A[0] |(* src = "alu.v:18.25-18.30" *)  B[0];
  assign _011_[1] = A[1] |(* src = "alu.v:18.25-18.30" *)  B[1];
  assign _015_[0] = _011_[4];
  assign _016_[0] = _011_[12];
endmodule
